FROM flink:1.18.0-scala_2.12-java11


RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev openjdk-11-jdk && \
    rm -rf /var/lib/apt/lists/*

RUN export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) && \
    echo "JAVA_HOME=${JAVA_HOME}" >> /etc/environment && \
    echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/profile.d/java.sh

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64

RUN ln -s /usr/bin/python3 /usr/bin/python

COPY requirements.txt .
RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt && \
    pip3 install apache-flink==1.18.0

WORKDIR /opt/flink/lib

ADD https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.0.1-1.18/flink-sql-connector-kafka-3.0.1-1.18.jar .
ADD https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.18/flink-connector-jdbc-3.2.0-1.18.jar .
ADD https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar .

WORKDIR /opt/flink
